version: "3"
services:
  hulk-buster-a:
    image: hulk-buster-a
    build: ./
    container_name: hulk-buster-a
    ports:
      - "3000:3000"
    restart: always
    networks:
      - net-alpha
    command: node dist/main.js

  nginx-alpha:
    image: nginx:latest
    container_name: nginx-alpha
    ports:
      - "80:80"
    restart: always
    networks:
      - net-alpha
    volumes:
      - /app-share/nginx-alpha:/etc/nginx


  mysql-alpha:
    image: mysql:latest
    container_name: mysql-alpha
    ports:
      - "3306:3306"
    restart: always
    networks:
      - net-alpha
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /app-share/mysql-alpha:/var/lib/mysql


networks:
  net-alpha:
    driver: bridge


